// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv-L86_hPwsjBPCx2RYy_LP6TPOsqWog0',
    appId: '1:917478262923:web:af2538cb6ba7c5157eac8e',
    messagingSenderId: '917478262923',
    projectId: 'utpmola',
    authDomain: 'utpmola.firebaseapp.com',
    storageBucket: 'utpmola.firebasestorage.app',
    measurementId: 'G-DJ1WWG6D0J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUfaHO-VIkV3_WJ_SPRXuC8TjuVGGQvyM',
    appId: '1:917478262923:android:b45cdbd2ae12e0e87eac8e',
    messagingSenderId: '917478262923',
    projectId: 'utpmola',
    storageBucket: 'utpmola.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYEMB8XEbA_B5vhvYD0m9oWBE9SIsmADo',
    appId: '1:917478262923:ios:eecfae2ca7a9302b7eac8e',
    messagingSenderId: '917478262923',
    projectId: 'utpmola',
    storageBucket: 'utpmola.firebasestorage.app',
    iosBundleId: 'com.example.utpmola',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYEMB8XEbA_B5vhvYD0m9oWBE9SIsmADo',
    appId: '1:917478262923:ios:eecfae2ca7a9302b7eac8e',
    messagingSenderId: '917478262923',
    projectId: 'utpmola',
    storageBucket: 'utpmola.firebasestorage.app',
    iosBundleId: 'com.example.utpmola',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv-L86_hPwsjBPCx2RYy_LP6TPOsqWog0',
    appId: '1:917478262923:web:f7be0c67bec312a37eac8e',
    messagingSenderId: '917478262923',
    projectId: 'utpmola',
    authDomain: 'utpmola.firebaseapp.com',
    storageBucket: 'utpmola.firebasestorage.app',
    measurementId: 'G-VMZ9C1M8LX',
  );
}
